// Code Examples for the Interactive Playground
const codeExamples = {
    lidar: {
        nos: `package robot_navigation
version "1.0.0"

node LidarProcessor {
    parameters {
        frame_id: string = "laser_frame"
        scan_topic: string = "/scan"
        publish_rate: float = 10.0 @range(1.0, 100.0)
        min_range: float = 0.1
    }
    
    subscriptions {
        scan: sensor_msgs::LaserScan @topic(\${scan_topic})
    }
    
    publications {
        processed: sensor_msgs::LaserScan @topic("/scan/processed")
    }

    on_init -> {
        self.get_logger().info("LidarProcessor initialized")
    }
    
    on on_scan_received(msg: sensor_msgs::LaserScan) -> {
        # Check scan data and republish
        if msg.range_min >= self.min_range:
            self.processed.publish(msg)
    }
}`,
        python: `# AUTO-GENERATED by NOS - Do not edit manually
# Source: robot_navigation.node

import rclpy
from rclpy.node import Node
from rclpy.qos import QoSProfile, ReliabilityPolicy, HistoryPolicy
from rcl_interfaces.msg import ParameterDescriptor, FloatingPointRange, IntegerRange
from nos.runtime import NOSNode, NOSLifecycleNode, create_qos_profile
from sensor_msgs.msg import *

class LidarProcessorBase(NOSNode):
    """Auto-generated base class for LidarProcessor node."""

    def __init__(self, node_name: str = 'lidar_processor'):
        super().__init__(node_name)

        # Parameter declarations
        self._declare_nos_parameters()

        # Setup communications
        self._setup_communications()

        # Call user initialization
        self.on_init()

    @property
    def frame_id(self):
        return self.get_parameter('frame_id').value

    @property
    def scan_topic(self):
        return self.get_parameter('scan_topic').value

    @property
    def publish_rate(self):
        return self.get_parameter('publish_rate').value

    @property
    def min_range(self):
        return self.get_parameter('min_range').value

    def _declare_nos_parameters(self):
        self.declare_parameter('frame_id', "laser_frame")
        self.declare_parameter('scan_topic', "/scan")
        self.declare_parameter('publish_rate', 10.0, descriptor=ParameterDescriptor(floating_point_range=[FloatingPointRange(from_value=1.0, to_value=100.0)]))
        self.declare_parameter('min_range', 0.1)

    def _setup_communications(self):
        self._scan_sub = self.create_subscription(
            LaserScan, self.scan_topic, self._on_scan_received, 10
        )

        self.processed = self.create_publisher(
            LaserScan, "/scan/processed", 10
        )

    def _on_scan_received(self, msg: LaserScan):
        """Wrapper for scan subscription callback."""
        try:
            self.on_scan_received(msg)
        except Exception as e:
            self.get_logger().error(f"Error in scan callback: {e}")

    def on_init(self):
        """User initialization callback."""
        try:
            self.get_logger().info("LidarProcessor initialized")
        except Exception as e:
            self.get_logger().error(f"Error in on_init callback: {e}")
            raise

    def on_scan_received(self, msg: LaserScan):
        """User callback: on_scan_received."""
        try:
            # Check scan data and republish
            if msg.range_min >= self.min_range:
                self.processed.publish(msg)
        except Exception as e:
            self.get_logger().error(f"Error in on_scan_received callback: {e}")
            raise`
    },
    lifecycle: {
        nos: `package robot_system

node CameraDriver {
    parameters {
        device_id: int = 0
        fps: int = 30 @range(1, 60)
    }
    
    publications {
        image: sensor_msgs::Image @topic("/camera/image") @qos(best_effort, depth=5)
    }
    
    lifecycle: managed
    
    on_init -> {
        self.get_logger().info("Camera node initialized but unconfigured")
    }

    on_shutdown -> {
        self.get_logger().info("Node clean shutdown completed")
    }
}`,
        python: `# AUTO-GENERATED by NOS - Do not edit manually
# Source: robot_system.node

import rclpy
from rclpy.node import Node
from rclpy.qos import QoSProfile, ReliabilityPolicy, HistoryPolicy
from rcl_interfaces.msg import ParameterDescriptor, FloatingPointRange, IntegerRange
from nos.runtime import NOSNode, NOSLifecycleNode, create_qos_profile
from sensor_msgs.msg import *

class CameraDriverBase(NOSLifecycleNode):
    """Auto-generated base class for CameraDriver node."""

    def __init__(self, node_name: str = 'camera_driver'):
        super().__init__(node_name)

        # Parameter declarations
        self._declare_nos_parameters()

        # Setup communications (handled in configure by lifecycle)
        self.on_init()

    @property
    def device_id(self):
        return self.get_parameter('device_id').value

    @property
    def fps(self):
        return self.get_parameter('fps').value

    def _declare_nos_parameters(self):
        self.declare_parameter('device_id', 0)
        self.declare_parameter('fps', 30, descriptor=ParameterDescriptor(integer_range=[IntegerRange(from_value=1, to_value=60)]))

    def _setup_communications(self):
        self.image = self.create_publisher(
            Image, "/camera/image", create_qos_profile(reliability='best_effort', depth=5)
        )

    def on_init(self):
        """User initialization callback."""
        try:
            self.get_logger().info("Camera node initialized but unconfigured")
        except Exception as e:
            self.get_logger().error(f"Error in on_init callback: {e}")
            raise

    def on_shutdown(self):
        """User shutdown callback."""
        try:
            self.get_logger().info("Node clean shutdown completed")
        except Exception as e:
            self.get_logger().error(f"Error in on_shutdown callback: {e}")
            raise

    def on_configure(self, state):
        """Configure the node."""
        self._setup_communications()
        return TransitionCallbackReturn.SUCCESS

    def on_activate(self, state):
        """Activate the node."""
        return TransitionCallbackReturn.SUCCESS

    def on_deactivate(self, state):
        """Deactivate the node."""
        return TransitionCallbackReturn.SUCCESS

    def on_cleanup(self, state):
        """Cleanup the node."""
        self.on_shutdown()
        return TransitionCallbackReturn.SUCCESS

    def on_shutdown_state(self, state):
        """Shutdown the node."""
        self.on_shutdown()
        return TransitionCallbackReturn.SUCCESS`
    },
    launch: {
        nos: `package navigation_system

launch RobotBringup {
    arguments {
        use_sim_time: bool = true
        autostart: bool = true
    }

    group sensors @namespace("sensors") {
        lidar: LidarDriver {
            use_sim: \${use_sim_time}
        }
        camera: CameraDriver {
            fps: 30
        }
    }

    container comp_container @name("nav_container") {
        filter: PointCloudFilter
        planner: PathPlanner
    }
}`,
        python: `# AUTO-GENERATED by NOS Launch Transpiler
# Source: navigation_system.launch
# Launch: RobotBringup

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, GroupAction, IncludeLaunchDescription
from launch.conditions import IfCondition, UnlessCondition
from launch.substitutions import LaunchConfiguration, TextSubstitution
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch_ros.actions import Node, ComposableNodeContainer
from launch_ros.descriptions import ComposableNode
from launch_ros.substitutions import FindPackageShare

def generate_launch_description():
    use_sim_time = LaunchConfiguration('use_sim_time')
    autostart = LaunchConfiguration('autostart')

    # Declare launch arguments
    declare_use_sim_time = DeclareLaunchArgument(
        'use_sim_time',
        default_value=True,
        description=''
    )
    declare_autostart = DeclareLaunchArgument(
        'autostart',
        default_value=True,
        description=''
    )

    # Launch actions
    actions = []

    group_action = GroupAction([
        Node(
            package='lidar_driver',
            executable='lidar_driver_node',
            name='lidar',
            parameters=[{'use_sim': use_sim_time}]
        ),
        Node(
            package='camera_driver',
            executable='camera_driver_node',
            name='camera',
            parameters=[{'fps': 30}]
        ),
    ], namespace="sensors")
    actions.append(group_action)

    container_action = ComposableNodeContainer(
        name="nav_container",
        namespace='',
        package='rclcpp_components',
        executable='component_container',
        composable_node_descriptions=[
            ComposableNode(
                package='point_cloud_filter',
                plugin='PointCloudFilter',
                name='filter'
            ),
            ComposableNode(
                package='path_planner',
                plugin='PathPlanner',
                name='planner'
            )
        ]
    )
    actions.append(container_action)

    return LaunchDescription([
        declare_use_sim_time,
        declare_autostart,
        group_action,
        container_action,
    ])`
    }
};

document.addEventListener('DOMContentLoaded', () => {
    // Theme Toggle
    const themeToggleBtn = document.getElementById('theme-toggle-btn');
    const body = document.body;
    
    // Check saved theme
    const savedTheme = localStorage.getItem('theme') || 'dark';
    body.setAttribute('data-theme', savedTheme);
    updateThemeIcon(savedTheme);
    
    themeToggleBtn.addEventListener('click', () => {
        const currentTheme = body.getAttribute('data-theme');
        const newTheme = currentTheme === 'dark' ? 'light' : 'dark';
        body.setAttribute('data-theme', newTheme);
        localStorage.setItem('theme', newTheme);
        updateThemeIcon(newTheme);
    });
    
    function updateThemeIcon(theme) {
        const iconSpan = themeToggleBtn.querySelector('span');
        if (theme === 'dark') {
            iconSpan.textContent = '☀️';
            iconSpan.setAttribute('title', 'Switch to Light Mode');
        } else {
            iconSpan.textContent = '🌙';
            iconSpan.setAttribute('title', 'Switch to Dark Mode');
        }
    }

    // Interactive Code Playground
    const tabButtons = document.querySelectorAll('.playground-tab-btn');
    const nosCodeEl = document.getElementById('nos-code-block');
    const pythonCodeEl = document.getElementById('python-code-block');
    
    function updatePlayground(exampleKey) {
        const example = codeExamples[exampleKey];
        if (example && nosCodeEl && pythonCodeEl) {
            nosCodeEl.textContent = example.nos.trim();
            pythonCodeEl.textContent = example.python.trim();
            
            // Reapply Prism syntax highlighting if available
            if (window.Prism) {
                Prism.highlightElement(nosCodeEl);
                Prism.highlightElement(pythonCodeEl);
            }
        }
    }
    
    if (nosCodeEl && pythonCodeEl) {
        tabButtons.forEach(btn => {
            btn.addEventListener('click', () => {
                tabButtons.forEach(b => b.classList.remove('active'));
                btn.classList.add('active');
                updatePlayground(btn.dataset.example);
            });
        });
        
        // Initialize playground with first tab
        updatePlayground('lidar');
    }

    // Simple Search Functionality
    const searchInput = document.getElementById('search-input');
    const sidebarLinks = document.querySelectorAll('.sidebar-link');
    
    if (searchInput) {
        searchInput.addEventListener('input', (e) => {
            const query = e.target.value.toLowerCase().trim();
            
            sidebarLinks.forEach(link => {
                const text = link.textContent.toLowerCase();
                const parentLi = link.parentElement;
                
                if (query === '' || text.includes(query)) {
                    parentLi.style.display = '';
                } else {
                    parentLi.style.display = 'none';
                }
            });
        });
    }

    // Set active link in sidebar based on current page URL
    const currentPath = window.location.pathname.split('/').pop() || 'index.html';
    sidebarLinks.forEach(link => {
        link.classList.remove('active');
        const linkPath = link.getAttribute('href');
        if (linkPath === currentPath) {
            link.classList.add('active');
        }
    });
});
